name: Basic Push Workflow

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Greeting
        run: echo "Hello from GitHub Actions"

      - name: Printing GITHUB_WORKSPACE VARIABLE
        run: echo "$GITHUB_WORKSPACE"

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Print Date
        run: date