name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:

      environment:
        description: "Deployment Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - production

      run_tests:
        description: "Run Tests Before Deploy?"
        required: true
        default: true
        type: boolean

      version:
        description: "Application Version"
        required: false
        default: "latest"
        type: string

jobs:

  manual-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Manual Inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Run Tests: ${{ inputs.run_tests }}"
          echo "Version: ${{ inputs.version }}"

      - name: Print Github Context Info
        run: |
          echo "Triggered By: ${{ github.actor }}"
          echo "Workflow Name: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"
          echo "Repository: ${{ github.repository }}"

      - name: Conditional Test Step
        if: ${{ inputs.run_tests == true }}
        run: echo "Running test suite..."

      - name: Deploy Step
        run: |
          echo "Deploying version ${{ inputs.version }} to ${{ inputs.environment }}"