name: Call Reusable Workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  call-build:

    uses: ./.github/workflows/08_reusable_workflow.yml

    with:
      message: "Hello from caller workflow"

    secrets:
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}