name: Reusable Workflow

on:
  workflow_call:
    inputs:
      message:
        description: "Message to print"
        required: true
        type: string

    secrets:
      MY_SECRET:
        required: false

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "${{ inputs.message }}"

      - name: Check secret
        run: |
          if [ -n "${{ secrets.MY_SECRET }}" ]; then
            echo "Secret exists"
          else
            echo "Secret not provided"
          fi