name: Terraform Infrastructure Pipeline

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

jobs:

  terraform-plan:

    if: github.event.inputs.action != 'destroy'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Auto Format Terraform
        run: terraform fmt -recursive

      - name: Commit Formatting Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Auto format Terraform code"
            git push
          else
            echo "No formatting changes needed"
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan